### ISSUE TITLE
Some unrealistic advice for SPA applications

### ISSUE THREAD

**Issue by hellsan631** [sitespeedio/coach#103]
I really like the tool, as it has pointed out some performance and accessibility gaps in a few of my applications. However, one piece of advice that its not accurate on is the 'Javascript Size' of my angular/react applications.

For Example:

> javascriptSize: The total Javascript transfer size is 288.6 kB and the uncompressed size is 880.2 kB. This is too much. You need to remove as much as possible.

I'm using gzip and js minification, and feel that the size of ~300kb is excellent, considering i'm compressing  23 different necessary vendor libraries (Angular, Stripe, Google Tag Manager, Sentry, etc) including the app scripts itself, a total 105 different scripts. As a baseline, I am comfortably below the [average website JS size](https://www.sitepoint.com/average-page-weight-increased-another-16-2015/) (363kb as of 2015, estimated +400kb in 2016).

I think the coach should give realistic advice in this area where spa applications are considered. Including analysis of gzip/minification should be present, and perhaps library detection as well? For instance, on separate website, i'm using both angular and react, or angular 1 and 2, or angular and jquery, and if multiple front-end libraries like this are detected, it should recommend that I only use one.

**Comment by beenanner** [comment]
@soulgalore I wonder if we can detect SPA sites automatically somehow and modify the rules like we do for h2. I guess the other options is to add an additional command line flag.

**Comment by hellsan631** [comment]
If there is information about the window and global variables, you can check to see if that library is defined. Something like ```if (angular || window.angular) then angular.is.enabled```

**Comment by soulgalore** [comment]
Hey @hellsan631 
thanks for the feedback! 

First we could maybe fine tune the numbers depending if you are testing on mobile or desktop. We could also have different values depending if the JS is async or not. But I think the best solution is what we have in Browsertime (the engine we use to run JS in the browser). We have a future that we haven't used yet, where we can run a script before we access the page we want to test = in this case it would be to access a URL. That would make it possible to measure the score for a second page (when JS is cached etc).  I think it would work perfect in Chrome, for Firefox there is (or at least was) a problem that a cached request is a 200 response in the HAR (https://github.com/tobli/browsertime/issues/121). But I think that it has been fixed don't know in which FF it will be released (we should check that).

A SPA page will always get bad for first access (like we measure today). But if we also can measure the second page (not repeat view) that will make it better.

Best
Peter

**Comment by soulgalore** [comment]
We have the <code>--preScript</code> but also lets add the <code>--preURL</code> that we have in Browsertime (accessing one URL before the one that the coach analyze), that way you can compare first hit and second URL.

**Comment by soulgalore** [comment]
This will automatically work now if you use the Coach in sitespeed.io (with the new scripting ability) and that is enough I think.

**Comment by hellsan631** [comment]
it's working great now, thanks
