### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by kristian-meyer** [sitespeedio/coach#104]
Is there a way to install coach in windows?  I got the following error below from the command prompt, it seems a simple enough problem, that the installer assumes '/' is the directory separator.

> webcoach@0.22.3 combine C:\Dev\coach
> mkdirp dist && tools/combine.js dist/coach.js

'tools' is not recognized as an internal or external command,
operable program or batch file.

[command line output.txt](https://github.com/sitespeedio/coach/files/276714/command.line.output.txt)

[npm-debug.log.txt](https://github.com/sitespeedio/coach/files/276715/npm-debug.log.txt)

**Comment by beenanner** [comment]
@kristian-meyer did you install via npm or did you use github and clone the project to your machine? The npm install is the preferred method unless you are doing development. 

I tested the global npm install of webcoach on my Windows 10 and it seems to work for me.

 `npm install -g webcoach` then `webcoach https://google.com/`

If you used the git clone method you can install it without the dev dependencies and it should work. Though again I'd recommend installing using the above npm method if you are just looking to use the tool.

`npm install --production` then `node bin\webcoach.js https://google.com/`

**Comment by kristian-meyer** [comment]
I had that error when I cloned the project to my machine first.  Using npm install worked, thanks.

**Comment by soulgalore** [comment]
could be that the setup doesn't work on Windows for now, would love PR:s that makes it work.

**Comment by XhmikosR** [comment]
@soulgalore: any hints why it breaks on Windows?

**Comment by XhmikosR** [comment]
Nevermind, I saw the error. How would you like to solve this? We could go with shell.js.

On a side note, I'm getting another error on Windows, I'll make a new issue.

**Comment by XhmikosR** [comment]
OK, it was simpler than I thought. See #117.
