### ISSUE TITLE
Firefox requirement?

### ISSUE THREAD

**Issue by psyked** [sitespeedio/coach#107]
Is Firefox an absolute requirement for *coach*, and should it be listed as such in the ReadMe file? Working with a fresh install I was presented with `BrowserError: Could not locate Firefox on the current system` and a subsequent failure.  Should *coach* continue, or fail at this point?

**Comment by soulgalore** [comment]
yep we should come cleaner with that: you will need Firefox or Chrome. If you have time we love a PR for the readme :)

**Comment by psyked** [comment]
In your defense the readme does actually say that Firefox and/or Chrome are required and that Firefox is the default (https://github.com/sitespeedio/coach#standalone), but perhaps the command line experience could be better!
