### ISSUE TITLE
Add a no color command line switch

### ISSUE THREAD

**Issue by bronzehedwick** [sitespeedio/coach#110]
I'd like the an option on the command line to turn off color output in the table view, with something like `--no-color`. I would like to generate reports using this tool, but the ANSI color codes make the output hard to read.

**Comment by soulgalore** [comment]
Hey @bronzehedwick ,
good idea, lets see how we can fix that.

Best
Peter

**Comment by tobli** [comment]
Quick implementation note: since we use chalk it should be as easy as using https://www.npmjs.com/package/chalk#chalkenabled. Patches welcome! =)

**Comment by bronzehedwick** [comment]
Excellent, I'll take a crack at this.
