### ISSUE TITLE
Allow overriding browser location

### ISSUE THREAD

**Issue by bronzehedwick** [sitespeedio/coach#111]
Coach doesn't find Firefox/Chrome if they were installed with homebrew cask. Paths are in the form of `/opt/homebrew-cask/Caskroom/firefox/[version]/Firefox.app`

**Comment by soulgalore** [comment]
@bronzehedwick does it work out of the box with other tools? We use Selenium/Chromedriver with Browsertime. Can you share the log (if you get any), else if you could try out standalone [Browsertime 1.0 branch](https://github.com/tobli/browsertime/tree/1.0) with the verbose log to just see what happens. Thanks!

**Comment by tobli** [comment]
Hi!
Browsertime has a feature to override the default location of Firefox (and Chrome). We just haven't gotten around to exposing that via the coach yet. Awaiting that, making a symlink should work, ugly as it might be.

**Comment by bronzehedwick** [comment]
Yeah, I used a symlink to get it working.

**Comment by soulgalore** [comment]
Low prio let us close it.
