### ISSUE TITLE
Find workaround for h2 test with chrome >= 51 and node 4

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/coach#114]
With [Chrome 51 h2 no longer works with NPN](https://developers.google.com/web/updates/2016/04/chrome-51-deprecations?hl=en#remove-tls-next-protocol-negotiation-npn) causing one of the tests to fail due to needing ALPN which is only supported in node.js >= 5.0 while using the [http2 module](https://www.npmjs.com/package/http2) for running tests.

**Comment by soulgalore** [comment]
so I guess ALPN worked in 4.4.4 but that was just luck then, I've missed that is 5 only when I added it to the project.

**Comment by tobli** [comment]
Since this is purely a test issue I'd say we just disable these tests on node 4. It's only 4 months until node 6 will be the LTS version, so I don't think it's worth spending too much time on.

**Comment by soulgalore** [comment]
sounds good.

**Comment by tobli** [comment]
Time heals all wounds. Or at least makes issues irrelevant once in a while.
