### ISSUE TITLE
Add AppVeyor support for Windows testing

### ISSUE THREAD

**Issue by XhmikosR** [sitespeedio/coach#118]
I will try setting things up later today or tomorrow.

**Comment by soulgalore** [comment]
Hey @XhmikosR that would be super, we tried that before with sitespeed.io but never got it to work.

**Comment by XhmikosR** [comment]
I'll make the tests under my account and if everything goes well, you will then add AppVeyor under your account and we'll make the switch.

**Comment by soulgalore** [comment]
I think we can skip this, we tried AppVeyor on sitespeed.io but we never acted on it.
