### ISSUE TITLE
cacheHeadersLong wrong info?

### ISSUE THREAD

**Issue by XhmikosR** [sitespeedio/coach#125]
So, I'm using [Apache Server Configs](https://github.com/h5bp/server-configs-apache) as my boilerplate.

```apache
ExpiresByType image/png  "access plus 1 month"
```

Yet coach complains that it's less than a month. Checking the headers with curl, I get

```
curl -Il https://cdn.mpc-hc.org/assets/fonts/fontawesome-webfont-4.6.3.woff2
date: Fri, 03 Jun 2016 12:07:15 GMT
last-modified: Sun, 29 May 2016 08:14:10 GMT
cache-control: max-age=2592000
expires: Tue, 28 Jun 2016 08:21:05 GMT
```

Since those are served via MaxCDN, I wonder if the time difference is to blame.

/CC @jdorfman

**Comment by jdorfman** [comment]
@XhmikosR what do you have your cache settings set at? It might be doing an override.

**Comment by XhmikosR** [comment]
@jdorfman: 1 month, no override.

**Comment by soulgalore** [comment]
Hey @XhmikosR 
the definition of a month right now in the coach is 30.43 days. Lets see if we can find a good value.

Best
Peter

**Comment by XhmikosR** [comment]
@soulgalore: thanks now it's correct.

@jdorfman: sorry for the noise.
