### ISSUE TITLE
`--noColor` still outputs color characters

### ISSUE THREAD

**Issue by XhmikosR** [sitespeedio/coach#126]
I was trying `node bin\webcoach.js https://mpc-hc.org/ --noColor --details>results.txt` and I notice that whenever `chalk.inverse` is used I get some weird characters in the text.

Example:

```
[7mINFORMATION[27m
```

Screenshot:
![char](https://cloud.githubusercontent.com/assets/349621/15778482/27575c9c-299f-11e6-9fab-2654f5409495.png)

I see the same results with Notepad++.

**Comment by XhmikosR** [comment]
Also, `--output=out.txt` has all color info in it. Is that intended?

**Comment by bronzehedwick** [comment]
Hi @XhmikosR sorry this is coming so late;  I added the `--noColor` option a bit ago and neglected to watch the repo. Following now, and I'll take a look.

**Comment by sumeetrohra** [comment]
@soulgalore I checked the source of this issue, --noColor  option is working, but when we output to some file, the file prints some random encoding bits, and that is an issue with cli-tables library (I was able to reproduce it with a basic example), I can make a small hack using regex to write the data correctly, should I use regex? or do you prefer something else?

**Comment by soulgalore** [comment]
Cool, great work @sumeetrohra !
