### ISSUE TITLE
Info: Requests and Sizes

### ISSUE THREAD

**Issue by A5hleyRich** [sitespeedio/coach#19]
I would love to see requests and sizes added to the info for the following assets:

- Total
- CSS
- JS
- Font
- Images

**Comment by A5hleyRich** [comment]
Happy to take this on if you're happy for it to be included.

**Comment by soulgalore** [comment]
Hey @A5hleyRich ,
cool. How do use the coach, only the JS or the combined JS/HAR? When we use the HAR we have that info already using https://github.com/sitespeedio/snufkin but we haven't exposed it in the output. I only thought of how we would use it in sitespeed.io but maybe that would be good so we expose it here to. Ping @tobli .

Best
Peter

**Comment by A5hleyRich** [comment]
I'm using the combined JS/HAR.

**Comment by soulgalore** [comment]
Cool. So in a couple of days ... weeks .. no days hopefully the 4.0 branch of sitespeed.io will be on Github and then we can have a look there see if that's what you need? Do you need the info or do plan to build something on top of the coach? If you just need the info, sitespeed.io will do. Else lets sync up and see how we can fix it.

**Comment by A5hleyRich** [comment]
I'm looking at integrating Coach into a project I'm working on. I currently use YSlow, but Coach seems better in every respect. Great work btw! 

I didn't realise Snufkin gathered that information, but that would require me to generate a separate HAR and then pass it to Snufkin, I believe?

**Comment by soulgalore** [comment]
It depends how you run: if you pass a URL, the coach will open Browsertime, run the JS, get the HAR from Browsertime and use that. We use it here: https://github.com/sitespeedio/coach/blob/6012b57889be099ab7f1821ae40d76d3281905e1/index.js#L38 
We should then make it configurable so also that object from snufkin also is exposed. If you feel that you have the time to do it, that's great :)

**Comment by A5hleyRich** [comment]
I'll give it a go. I'm fairly new to node so bear with me!
