### ISSUE TITLE
Bookmarklet

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/coach#2]
It would be great if the coach could be a bookmarklet. We done the concatenation and logs all the data to the console. But what we really want is a HTML-bookmarklet.

I'm a fan of the [DOM monster](http://mir.aculo.us/dom-monster/) something like that would be cool. A summary first, displaying when you got a score below 100. Or something :)

**Comment by tobli** [comment]
A first version of the bookmarklet is in place. It's created at build time in the dist folder, but also uploaded to GitHub Releases on each release (e.g. https://github.com/sitespeedio/coach/releases/tag/v0.1.9). Closing this issue for now, we can open follow up issues for more specific additions to the bookmarklet.
