### ISSUE TITLE
Info: Screenshot

### ISSUE THREAD

**Issue by A5hleyRich** [sitespeedio/coach#20]
Ability to return a screenshot of the rendered page as binary data. Possibly add the `-s` option to toggle the inclusion. Similar to what PageSpeed does.

**Comment by soulgalore** [comment]
Yes, so we will have it sitespeed.io using Browsertime, but maybe we could do so can pass CLI parameters to Browsertime (that we use to run the browser), so it's also available for the coach. We haven't implemented it yet though in Browsertime :) It should be pretty easy using Selenium but it's nothing we have had time to look at yet.

**Comment by A5hleyRich** [comment]
Closing as feature falls out of scope.

**Comment by soulgalore** [comment]
We have this in Browsertime so lets add it to the coach.

**Comment by tobli** [comment]
Saving a screen shot is now possible by running 
```sh
webcoach --screenshot <url>
```
The coach api also supports screenshots by passing screenshot:true in the options object.
