### ISSUE TITLE
Reporting misconfigured mime types

### ISSUE THREAD

**Issue by lbod** [sitespeedio/coach#204]
I raised this initially over at https://github.com/sitespeedio/sitespeed.io/issues/792 and it was suggested by @beenanner it might be good to add as a rule to the coach.

Having looked through the code it appears not much is needed other than adding a new advice. I'd like some feedback to understand if this is ok before I push the PR.

The HAR already reports an incorrect header via https://github.com/sitespeedio/pagexray/blob/master/lib/util.js#L20 so it appears that's all you need to test against i.e. "other". 
Initially I looked at requiring something like https://github.com/jshttp/mime-types and testing against the asset.headers.response.content-type property, however it makes sense to rely on pagexray making that decision instead?

If the above is fine the other questions I have is about weight and score. I'd suspect this is a "low weight" i.e. 1 or 2 and the score decremented by 1 for each asset with an incorrect mime type?

If that's all ok I'll do the pr tonight or tomorrow.

**Comment by beenanner** [comment]
@Ibod if you could start by making the weight 0 for now that will be good enough. We can change it later, but initially it will be good to have to inform the user. I would like to think on scoring it a bit more since some sites will not have totally control over all assets.

**Comment by lbod** [comment]
@beenanner Ok will do. I'm struggling to remember where I was with this as there wasn't a quick reply but what I do remember is I spent time debugging what looks to be a bug tagging the advice as `bestpractice` and getting the results to update best practice accordingly. 
I got slightly lost debugging all the promises but after moving the advice into a new `bestpractice` folder, the advice was executed but not reported correctlt in `lib/har/index.js`

I'm thinking that is a separate bug and for the moment just add mime type reporting as a performance advice?

**Comment by beenanner** [comment]
Sounds good @lbod. Maybe @soulgalore has some thoughts that could help you set this up as it would be a good use-case to improve the docs on how to add these for others in the future.

**Comment by tobli** [comment]
Hi @lbod!
The current code for built-in HAR advice is hard coding a single 'performance' category. I agree that a good start for a PR is to put the new check within the performance category, with a weight of 0, and opening a separate issue for the hard coding.

Thanks!

**Comment by lbod** [comment]
Hi @tobli and thanks. I forgot about tests so just doing that now as well as understanding how your tests are setup.

What's your normal process for adding/generating the test har files? How are you generating those files? 

They're very large files, I was going to re-use the `www.sitespeed.io-redirecting-to-https.har` file because it's much smaller but really, I just want the smallest test har file possible with expected success/fail content. I was worried I may not understand the reasoning e.g. you want to generate a har against an actual live page

**Comment by tobli** [comment]
@lbod - no worries, you're not missing any important underlying reason. We just took files we had and knew, more or less. =)
So feel free to provide reduced, test case specific har files. Whatever we think makes most sense.

Thanks for contributing!

**Comment by beenanner** [comment]
Thanks @lbod!

**Comment by lbod** [comment]
no problem @beenanner .. it's nice to see you're so open to PR's. I'll have a look to see if there's any bugs or features I could contribute to

**Comment by beenanner** [comment]
@lbod absolutely and thank you for contributing! :-)
