### ISSUE TITLE
Add CLI option to control viewport size

### ISSUE THREAD

**Issue by jsocol** [sitespeedio/coach#208]
For responsive sites it's important to be able to be deterministic about viewport size. I'd approach this by making two small changes:

* Add a `--viewPort` option in [lib/cli.js](https://github.com/sitespeedio/coach/blob/master/lib/cli.js#L65) that took a `WIDTHxHEIGHT` argument.
* Update the `--mobile` option to [not overwrite](https://github.com/sitespeedio/coach/blob/master/bin/webcoach.js#L19) the `--viewPort` value if it was set by the user.

If this sounds good I'm happy to open a PR!

**Comment by soulgalore** [comment]
Hey @jsocol yes that sounds great, we haven't done that yet, a PR would be super thanks!

**Comment by jsocol** [comment]
@soulgalore Opened #209, thanks!
