### ISSUE TITLE
Add the ability to sort the adviceInfo table

### ISSUE THREAD

**Issue by lapa182** [sitespeedio/coach#222]
I think we should be able to sort the advices just like the files in the tablet list, this can make the developer life easier to prioritise the fixes/enchantments.

**Comment by soulgalore** [comment]
hey @lapa182 yes sorting by highest or lowest score should be best right? Now it's sorted by name of the advice, I think we should keep that and add the possibility to sort by score. Do you have time to do a PR?

**Comment by lapa182** [comment]
Sure, @soulgalore, I don't know if supposed to be that way but I'm going to open the PR with the change.

**Comment by lapa182** [comment]
PR was raised :)

**Comment by tobli** [comment]
Thanks for the reminder, I'll have a look.

**Comment by lapa182** [comment]
This was merged in https://github.com/sitespeedio/coach/pull/223
