### ISSUE TITLE
Option to save .har file

### ISSUE THREAD

**Issue by A5hleyRich** [sitespeedio/coach#27]
Is this something you guys would be interested in adding to Coach? I propose a new option which accepts a file path and saves the generated .har file?

`webcoach -u http://www.sitespeed.io --browser firefox --har /path/to/output.har`

I've implemented this locally, but thought I'd ask before raising a PR.

**Comment by soulgalore** [comment]
Hey @A5hleyRich I think we will try to keep the coach as minimal as possible. What's missing is a description/summary of what all the different tools will do and what's their responsibility, we'll try to start on that next week. 

Been thinking and maybe you should use Browsertime straight off for what your building and then use the coach from that instead? Then you can have the HAR etc,

Best
Peter

**Comment by A5hleyRich** [comment]
Thanks for the advice Peter. I think you're right, then I can pass the generated HAR from Browsertime to Coach and Snufkin as required.
