### ISSUE TITLE
use sitespeed and coach simultaneously from a node app

### ISSUE THREAD

**Issue by Adesh** [sitespeedio/coach#291]
is there a way to run webcoach simultaneously while testing a web page through sitespeed in node app?

**Comment by Adesh** [comment]
Yes. But how to find recommendations in a node environment?

**Comment by soulgalore** [comment]
You can have a look at the [Grunt plugin](https://github.com/sitespeedio/grunt-sitespeedio/blob/master/tasks/sitespeedio.js) it hasn't been updated to 7.0 yet but I don't think there should be an issue.

Best
Peter
