### ISSUE TITLE
optimalCssSize, negative score

### ISSUE THREAD

**Issue by amic81** [sitespeedio/coach#297]
Hi,

after doing a scan, in the advice of the coach I noticed that for the entry optimalCssSize the score value can fall below 0, in my case it arrived at -10 ...

is this correct or 0 should be the limit and not go negative?

Thank you

**Comment by soulgalore** [comment]
Hi @amic81 thank you for creating the issue, yep that sounds wrong. Let me have a look this weekend.

Best
Peter

**Comment by soulgalore** [comment]
This is fixed in the coming release, thank you @amic81 for submitting the issue!

**Comment by amic81** [comment]
Hi, thanks to you!
