### ISSUE TITLE
What is the best tool to visualize this data for now

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/coach#30]

**Comment by soulgalore** [comment]
There's no super good way today except looking in the JSON.

Either you can use the bookmarklet and check the console, then it's at least ok to check things (but you miss the advice from the HAR).

Else you can use https://stedolan.github.io/jq/ to parse the JSON and get the values you want.

**Comment by tobli** [comment]
Before too long Sitespeed 4 (still early in development) will be available to try out. With that you'll be able to push data to graphite, which will allow for powerful graphing, e.g. using Grafana.

**Comment by soulgalore** [comment]
Hey @softwareklinic I've pushed #43 that makes the output from the CLI easier to understand. Still need some fixes but it is at least readable.

**Comment by softwareklinic** [comment]
Cool will check it out

Sent from my iPhone

On Mar 19, 2016, at 1:57 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @softwareklinic<https://github.com/softwareklinic> I've pushed #43<https://github.com/sitespeedio/coach/issues/43> that makes the output from the CLI easier to understand. Still need some fixes but it is at least readable.

**Comment by soulgalore** [comment]
closing this now, the cli table output is nice.
