### ISSUE TITLE
[mimeTypes] False positive for OGG MIME type

### ISSUE THREAD

**Issue by znerd** [sitespeedio/coach#302]
Currently [mimeTypes] complains about an `.ogg` file having an incorrect MIME type when it is `audio/ogg`.

However, according to these documents, that MIME type is correct:
- https://gingertech.net/2008/09/05/new-ogg-mime-types-ratified/
- http://www.ietf.org/rfc/rfc5334.txt

Sample:
- https://static.olark.com/jsclient/sounds/olark-chimes.ogg

Context:
- SiteSpeed.io 7.4.0 (with Coach 2.2.0)

**Comment by soulgalore** [comment]
Hi @znerd thanks for creating the issue! I think the problem comes from PageXray, it's there each response is categorized: https://github.com/sitespeedio/pagexray/blob/master/lib/util.js#L6-L21

Any change you can do a PR and update it? 
Thanks 
Peter

**Comment by soulgalore** [comment]
Hmm that advice seems to not be so correct since it relays on things specified in PageXray. Let me fix that later on and for now update page xray.

**Comment by znerd** [comment]
> Any change you can do a PR and update it?

While I started looking into it I noticed you beat me to it – thanks 👍 

I guess all that's remaining here is that the dependency version is bumped, and then a new Coach release?

**Comment by soulgalore** [comment]
I had time to fix that yesterday so it went out with 2.3.0. New sitespeed.io will be released on Wednesday.

**Comment by sumeetrohra** [comment]
@soulgalore this issue is fixed.

**Comment by soulgalore** [comment]
Thanks @sumeetrohra for noticing!
