### ISSUE TITLE
Issue Testing non '.com' domains

### ISSUE THREAD

**Issue by xanderstephens125** [sitespeedio/coach#303]
I am attempting to test sites in several different domains (i.e. .ca, .fr, .com) with standalone mode. The .com test runs as expected, but any other domain of the same site gives the following error:

`ERROR: UrlLoadError: Failed to load/verify https://<site>.ca uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:200:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-10-15 18:26:16] INFO: 0
Error running advice:  TypeError: Cannot read property 'coach' of undefined
    at runBrowsertime.then.result (/usr/src/app/lib/index.js:118:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

I also ran the standalone against https://google.ca, which worked as expected. Is there some property I am overlooking that would cause Coach not to run against my sites?

Thank you.

**Comment by soulgalore** [comment]
Hi @xanderstephens125 no there's nothing built in that should stop you to test different domains. Could it be some kind of redirect that happens on those site depending on from where you test? If you can share one URL I can test at my end.

Best
Peter

**Comment by xanderstephens125** [comment]
@soulgalore thank you. I am attempting to test https://m.maccosmetics.ca

**Comment by xanderstephens125** [comment]
@soulgalore your first thought was correct, it is doing multiple redirects. If I hit the final site it works as expected. Thank you for your input.

**Comment by soulgalore** [comment]
Thanks @xanderstephens125 for sharing! I could reproduce if I run like this:
`/bin/webcoach.js https://m.maccosmetics.ca`

When I run it directly in sitespeed.io, it works. The difference is that we run the browsers headless (with the headless flag for Chrome/FF in the Coach). Let me dig into this and check what's causing it. In the mean time you can add the --mobile flag, that works for me at least:

/bin/webcoach.js https://m.maccosmetics.ca --mobile. There's something with the redirects that doesn't work hm.
