### ISSUE TITLE
Favicon coach score

### ISSUE THREAD

**Issue by SowmyaMastaiah** [sitespeedio/coach#312]
When executing sitespeed coach under performance advice -- "favicon" always has score "0" even though favicons are present on page. I tried to execute on many other URL's and faced same issue.

**Comment by soulgalore** [comment]
This was a bug in the current version, I've fixed it for the coming 3.0.

**Comment by SowmyaMastaiah** [comment]
Thank you!!

**Comment by soulgalore** [comment]
Closing this for 3.0
