### ISSUE TITLE
HTTP Authentication

### ISSUE THREAD

**Issue by cerebe** [sitespeedio/coach#347]
Unless I missed it in the docs, I couldn't find a way to run coach on websites which are protected with [HTTP Authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication).

Would that be a functionality that could be added?

**Comment by soulgalore** [comment]
Hi @cerebe I think all options are passed to Browsertime if you run through the cli, so you could use all of these: https://www.sitespeed.io/documentation/browsertime/configuration/ (`--basicAuth`).

At least in theory :)

Best
Peter

**Comment by cerebe** [comment]
Thanks for your answer, I think it's working but have auth access problem on my current test case even with browsertime.

I'll close this thread.
