### ISSUE TITLE
Webcoach's accessbility is not displayed.

### ISSUE THREAD

**Issue by yoodongsa** [sitespeedio/coach#374]
When using sitespeed.io, there was a case where accessibility was not output. 
But when I used it a few years ago, it worked. Did the usage change with the version change? 
Where can webcoach's advice be analyzed? thank you.

![image](https://user-images.githubusercontent.com/73861418/143517206-6db976e5-cf77-42cf-a2d5-22377273e230.png)

**Both the coach and chrome driver versions are up to date.**
chrome-driver version : 96.0.4664.45
coach version : 6.4.3

**Comment by soulgalore** [comment]
Hi @yoodongsa we removed accessibility advice in sitespeed.io 20/coach and started to use AXE-core instead (since it gives better advice). You can enable that with `--axe.enable` and the docs: https://www.sitespeed.io/documentation/sitespeed.io/axe/

**Comment by yoodongsa** [comment]
> 안녕하세요 @yoodongsa 는 sitespeed.io 20/coach에서 접근성 조언을 제거하고 대신 AXE-core를 사용하기 시작했습니다(더 나은 조언을 제공하기 때문에). `--axe.enable`다음 문서를 사용하여 활성화할 수 있습니다 . https://www.sitespeed.io/documentation/sitespeed.io/axe/
Can I use the accessbility if I downgrade the version?

**Comment by soulgalore** [comment]
Yes, but then you need to make sure you use a correct Chromedriver.

**Comment by yoodongsa** [comment]
thank you very much :)
