### ISSUE TITLE
README Hashlink not working

### ISSUE THREAD

**Issue by BurhanRaja** [sitespeedio/coach#378]
Hello! everyone.

I just wanted to address a small bug in the readme.md file. 
There are three hashlinks in your readme that is not working.

1. What do the coach do? - https://github.com/sitespeedio/coach#what-do-the-coach-do
2. How does it all work? - https://github.com/sitespeedio/coach#how-does-it-all-work?
3. Do my page need coaching? - https://github.com/sitespeedio/coach#do-my-page-need-coaching

I would request you to kindly assign me to this issue. Will love to contribute as small as possible.

**Comment by xit4** [comment]
I handled this in PR #379

**Comment by BurhanRaja** [comment]
Ok, no problem. 😅
