### ISSUE TITLE
Frontend for the bookmarklet

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/coach#39]
Today the bookmarklet just dumps the advice to the console log. Lets create a frontend for the bookmarklet.

**Comment by matthojo** [comment]
I'm currently building a Chrome Dev tools extension for this, I'm sure if it suffices the whole of the issue though. Does this need to work in all browsers to be marked as complete?

(https://github.com/matthojo/coach-devtools)

**Comment by tobli** [comment]
That's great @matthojo!
Browser extension and bookmarklet are both nice, I think there can be a place for both. With Firefox adopting the same extension api we could perhaps have an extension that works in two browsers.

Any thoughts on how to make maintenance (keeping up with new coach releases etc) as smooth as possible are also welcome. @soulgalore and I have started discussing this for the broader Sitespeed.io ecosystem (docker image building, testing as browsers update etc) but haven't really addressed it yet. We'd like to automate as much as possible, and make it easy for people to hack on top of our tools. All ideas and input are welcome.

**Comment by matthojo** [comment]
The Chrome Extension is now coming along nicely, it's still unlisted on the store whilst I'm testing it but I'm hoping to make it live-live later today. https://chrome.google.com/webstore/detail/coach-panel/olecfjmnejnkjipoicfpneceppjeaemo

Regarding maintenance, it's a difficult one. The problem with the Chrome extension is it takes the 'raw' Coach JS as it doesn't need the web drivers - similar to the bookmarklet version. So any updates will have to be manually moved over. I would love to have this workflow improved though. I'll have a think!

Here is a screenshot on current Coach Panel btw, any suggestion welcome!
![screen shot 2016-06-08 at 12 17 20](https://cloud.githubusercontent.com/assets/367517/15892863/2a32abb4-2d74-11e6-8d26-fcb5967186da.png)

**Comment by soulgalore** [comment]
Wow @matthojo looks great!!!! 

Really looking forward to when Chrome supports resource timing with weight per asset, then we can move some rules (and override them in the HAR advice).

**Comment by matthojo** [comment]
Yeh that will be awesome!
Just a heads up Coach Panel is now public and can be found by anyone on the Chrome Web Store 🎉

**Comment by soulgalore** [comment]
Wow that's great! Can you submit a PR with a link in the README?

**Comment by soulgalore** [comment]
@matthojo hmm I wonder if I have something that blocks it or did something wrong? I've installed it, it's greyd out and when i click "Coach Panel" I get to https://chrome.google.com/webstore/detail/coach-panel/olecfjmnejnkjipoicfpneceppjeaemo

<img width="208" alt="screen shot 2016-06-09 at 10 05 12" src="https://cloud.githubusercontent.com/assets/540757/15922755/af5d5f18-2e29-11e6-93e2-ca2f878b98a5.png">

**Comment by matthojo** [comment]
It's a Dev Tools panel, so appears alongside the other Chrome Dev Tools tabs.

I'm not sure how to remove that icon! I'll look into it further though..

**Comment by soulgalore** [comment]
Ahhh I see now, thanks :) Awesome work!!!!

**Comment by matthojo** [comment]
Glad you like it! :)
