### ISSUE TITLE
Error while running the url with webcoach

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/coach#8]
Keyurs-MacBook-Air:~ FamilyMac$ webcoach -u http://www.sitespeed.io --browser firefox
/usr/local/lib/node_modules/webcoach/bin/webcoach.js:5
let fs = require('fs'),
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by soulgalore** [comment]
Hey @softwareklinic 
did you get a warning when you installed it? It needs nodejs version  4.2.0 or later. The install should warn about that. I'll update the readme too.
Best
Peter

**Comment by softwareklinic** [comment]
Yes I did -
But keeps failing at let statement in js



Regards,
Keyur

On Feb 17, 2016, at 3:30 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @softwareklinic<https://github.com/softwareklinic>
did you get a warning when you installed it? It needs nodejs version 4.2.0 or later. The install should warn about that. I'll update the readme too.
Best
Peter

**Comment by soulgalore** [comment]
Hey @softwareklinic 
so which nodejs version are you running? :)

Best
Peter

**Comment by softwareklinic** [comment]
I downloaded the latest last week... I can check the version.. but initially it was showing me warnings that the version is old... so i updated to latest.

**Comment by softwareklinic** [comment]
node is 

Keyurs-MacBook-Air:coach FamilyMac$ sudo n stable

     install : node-v5.6.0
       mkdir : /usr/local/n/versions/node/5.6.0
       fetch : https://nodejs.org/dist/v5.6.0/node-v5.6.0-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v5.6.0

Keyurs-MacBook-Air:coach FamilyMac$ node -v
v5.6.0

**Comment by tobli** [comment]
Closing this, since it shouldn't be a problem with a recent version of the coach. Please re-open if you still have the same issue.

I just successfully tested the following:
```sh
nvm use 5.6.0
webcoach http://www.sitespeed.io --browser firefox
```
